name: components
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - mlflow=1.20.2
  - pyyaml=6.0
  - pip=21.2.4
  - python=3.8.10
  - pytorch=1.6.0
  - torchvision=0.10.1
  - mlflow=1.20.2
